### ISSUE TITLE
useI18n(); in setup function throws error

### ISSUE THREAD

**Issue by karladler** [intlify/vue-i18n-composable#14]
calling useI18n() in composition API setup creates an error, since I updated my versions.

```typescript
import { useI18n } from 'vue-i18n-composable';
// ... 

export default defineComponent({
  // ...
  setup(props) {
    const { t } = useI18n();
```

creates this:

> [Vue warn]: Error in data(): "Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function."

Versions:
vue-i18n: 8.26.5
 vue-i18n-composable@npm:0.2.2

main.ts (minimal version)
```typescript
import Vue from 'vue';
import VueCompositionApi from '@vue/composition-api';
import de from '../locales/de.json';
import { createI18n } from 'vue-i18n-composable';

Vue.use(VueCompositionApi);

const i18n = createI18n({
  silentFallbackWarn: true,
  locale:  'de',
  fallbackLocale: 'de',
  messages: { de },
});

new Vue({
  render: (h) => h(App),
  i18n,
}).$mount('#app');

```
Is this still the correct way to use i18n programatically?

Edit: updated usage if of  useI18n(); and added main.ts

**Comment by xitrox** [comment]
Struggling with the same problem.
Also it's the same behavior for me when I use the [example](https://github.com/intlify/vue-i18n-composable/blob/master/README.md) and just:
`  setup() {
    return {
      ...useI18n()
    }
}`

Would like to add more value to this but can't since I'm also using the same versions.

**Comment by cyio** [comment]
@karladler @xitrox 

solved problem for me

```js
import { useI18n } from 'vue-i18n-composable/src/index'

import { createI18n } from 'vue-i18n-composable/src/index'
```

**Comment by VisonM** [comment]
Has anyone solved this problem？Struggling with the same problem when i run example in this project.
I think that if the example on the repository cannot run normally, at least they should be marked as unavailable first, otherwise it will cause a lot of confusion.

**Comment by Hienphamthe** [comment]
the trick from @cyio works for me

**Comment by VisonM** [comment]
see https://github.com/vuejs/composition-api/pull/837

**Comment by nagisaando** [comment]
@kingyue737 Did you try https://github.com/intlify/vue-i18n-composable/issues/14#issuecomment-974661848? I am using vitest as well, but changing path in all vue files fixed error

**Comment by dawid-polak** [comment]
I solved this problem by installing the latest version of i18n. 
command: `npm install vue-i18n@9`
