### ISSUE TITLE
Is it also possible to use `vue-I18n@next` with Vue 2?

### ISSUE THREAD

**Issue by DarkLite1** [intlify/vue-i18n-composable#4]
We're [struggling](https://stackoverflow.com/questions/65122796/how-to-create-a-quasar-framework-boot-file-for-vuei18nnext-with-the-vue-composi?noredirect=1#comment115131863_65122796) a bit with setting up `vue-i18n@next` with Vue 2 and the Vue Composition API.  On Vue 2 the following is not available as described in the [docs](https://vue-i18n-next.intlify.dev/api/general.html#returns):

```typescript
import { createApp } from 'vue'
```
Are we supposed to use this plugin instead? Thank you for the clarification and sorry if this is wrong place to ask.

**Comment by oiltofu** [comment]
try
import { createApp } from "@vue/composition-api";
