### ISSUE TITLE
Can't import the named export 'computed' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by oiltofu** [intlify/vue-i18n-composable#8]
i exct the README step and run my APP and then err:

 error  in ./node_modules/vue-i18n-composable/dist/index.mjs
Can't import the named export 'computed' from non EcmaScript module (only default export is available)

someone like this? how to fix it?

**Comment by oiltofu** [comment]
it seems vue-cli's problem

**Comment by dnasir** [comment]
How did you get it to work?

**Comment by kuroski** [comment]
It seems some dependency is making use of mjs, you can work around that by updating your vue.config:

```
// vue.config.js

module.exports = {
  // ...
  chainWebpack: config => {
    // ...
    config.resolve
      .extensions
        .prepend('.mjs')

    config.module
      .rule('mjs')
        .test(/\.mjs$/)
        .include
          .add(/node_modules/)
          .end()
        .type('javascript/auto')
      // ...
  },
  // ...
}
```
